# Use the official micromamba image as a base
FROM continuumio/miniconda3:latest
LABEL maintainer="Miguel A. Ibarra-Arellano"

# Set the base layer for micromamba
COPY environment-mac.yml .

# Update package manager and install essential build tools
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    ffmpeg \
    libsm6 \
    libxext6 \
    procps

# Install dependencies with micromamba, clean afterwards
RUN conda env create -f environment-mac.yml \
    && conda clean --all --yes

# Add environment to PATH
ENV PATH="/opt/conda/envs/stardist/bin:$PATH"

# Set the working directory
WORKDIR /stardist