name: stardist
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.9  ## specify desired version
  - tensorflow-deps==2.10.0
  - stardist
  - tifffile<2022.4.22
  - pip
  - pip:
    - tensorflow-macos==2.10.0
    - tensorflow-metal==0.6.0